// Code generated by protoc-gen-go.
// source: MSG_CenterGate.proto
// DO NOT EDIT!

/*
Package MSG_CenterGate is a generated protocol buffer package.

It is generated from these files:
	MSG_CenterGate.proto

It has these top-level messages:
	CS_PlayerOnline_Req
	SC_PlayerOnline_Rsp
	CS_PlayerOffline_Req
	SC_PlayerOffline_Rsp
	CS_GetBroadCastSessions_Req
	SC_GetBroadCastSessions_Rsp
*/
package MSG_CenterGate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefan
// server
type SUBMSG int32

const (
	SUBMSG_Begin                   SUBMSG = 0
	SUBMSG_CS_PlayerOnline         SUBMSG = 1
	SUBMSG_SC_PlayerOnline         SUBMSG = 2
	SUBMSG_CS_PlayerOffline        SUBMSG = 3
	SUBMSG_SC_PlayerOffline        SUBMSG = 4
	SUBMSG_CS_GetBroadCastSessions SUBMSG = 5
	SUBMSG_SC_GetBroadCastSessions SUBMSG = 6
)

var SUBMSG_name = map[int32]string{
	0: "Begin",
	1: "CS_PlayerOnline",
	2: "SC_PlayerOnline",
	3: "CS_PlayerOffline",
	4: "SC_PlayerOffline",
	5: "CS_GetBroadCastSessions",
	6: "SC_GetBroadCastSessions",
}
var SUBMSG_value = map[string]int32{
	"Begin":                   0,
	"CS_PlayerOnline":         1,
	"SC_PlayerOnline":         2,
	"CS_PlayerOffline":        3,
	"SC_PlayerOffline":        4,
	"CS_GetBroadCastSessions": 5,
	"SC_GetBroadCastSessions": 6,
}

func (x SUBMSG) String() string {
	return proto.EnumName(SUBMSG_name, int32(x))
}
func (SUBMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorCode int32

const (
	ErrorCode_Invalid ErrorCode = 0
	ErrorCode_Success ErrorCode = 1
	ErrorCode_Fail    ErrorCode = 2
)

var ErrorCode_name = map[int32]string{
	0: "Invalid",
	1: "Success",
	2: "Fail",
}
var ErrorCode_value = map[string]int32{
	"Invalid": 0,
	"Success": 1,
	"Fail":    2,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// CS_PlayerOnline
type CS_PlayerOnline_Req struct {
	PlayerIdentify string `protobuf:"bytes,1,opt,name=PlayerIdentify" json:"PlayerIdentify,omitempty"`
}

func (m *CS_PlayerOnline_Req) Reset()                    { *m = CS_PlayerOnline_Req{} }
func (m *CS_PlayerOnline_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerOnline_Req) ProtoMessage()               {}
func (*CS_PlayerOnline_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// SC_PlayerOnline
type SC_PlayerOnline_Rsp struct {
	Ret            ErrorCode `protobuf:"varint,1,opt,name=Ret,enum=MSG_CenterGate.ErrorCode" json:"Ret,omitempty"`
	PlayerIdentify string    `protobuf:"bytes,2,opt,name=PlayerIdentify" json:"PlayerIdentify,omitempty"`
}

func (m *SC_PlayerOnline_Rsp) Reset()                    { *m = SC_PlayerOnline_Rsp{} }
func (m *SC_PlayerOnline_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerOnline_Rsp) ProtoMessage()               {}
func (*SC_PlayerOnline_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// CS_PlayerOffline
type CS_PlayerOffline_Req struct {
	PlayerIdentify string `protobuf:"bytes,1,opt,name=PlayerIdentify" json:"PlayerIdentify,omitempty"`
}

func (m *CS_PlayerOffline_Req) Reset()                    { *m = CS_PlayerOffline_Req{} }
func (m *CS_PlayerOffline_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerOffline_Req) ProtoMessage()               {}
func (*CS_PlayerOffline_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// SC_PlayerOffline
type SC_PlayerOffline_Rsp struct {
	Ret            ErrorCode `protobuf:"varint,1,opt,name=Ret,enum=MSG_CenterGate.ErrorCode" json:"Ret,omitempty"`
	PlayerIdentify string    `protobuf:"bytes,2,opt,name=PlayerIdentify" json:"PlayerIdentify,omitempty"`
}

func (m *SC_PlayerOffline_Rsp) Reset()                    { *m = SC_PlayerOffline_Rsp{} }
func (m *SC_PlayerOffline_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerOffline_Rsp) ProtoMessage()               {}
func (*SC_PlayerOffline_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// CS_GetBroadCastSessions
type CS_GetBroadCastSessions_Req struct {
	PlayerIdentifys []string `protobuf:"bytes,1,rep,name=PlayerIdentifys" json:"PlayerIdentifys,omitempty"`
	Data            []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *CS_GetBroadCastSessions_Req) Reset()                    { *m = CS_GetBroadCastSessions_Req{} }
func (m *CS_GetBroadCastSessions_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_GetBroadCastSessions_Req) ProtoMessage()               {}
func (*CS_GetBroadCastSessions_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// SC_GetBroadCastSessions
type SC_GetBroadCastSessions_Rsp struct {
	Ret             ErrorCode `protobuf:"varint,1,opt,name=Ret,enum=MSG_CenterGate.ErrorCode" json:"Ret,omitempty"`
	PlayerIdentifys []string  `protobuf:"bytes,2,rep,name=PlayerIdentifys" json:"PlayerIdentifys,omitempty"`
	Data            []byte    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *SC_GetBroadCastSessions_Rsp) Reset()                    { *m = SC_GetBroadCastSessions_Rsp{} }
func (m *SC_GetBroadCastSessions_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_GetBroadCastSessions_Rsp) ProtoMessage()               {}
func (*SC_GetBroadCastSessions_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*CS_PlayerOnline_Req)(nil), "MSG_CenterGate.CS_PlayerOnline_Req")
	proto.RegisterType((*SC_PlayerOnline_Rsp)(nil), "MSG_CenterGate.SC_PlayerOnline_Rsp")
	proto.RegisterType((*CS_PlayerOffline_Req)(nil), "MSG_CenterGate.CS_PlayerOffline_Req")
	proto.RegisterType((*SC_PlayerOffline_Rsp)(nil), "MSG_CenterGate.SC_PlayerOffline_Rsp")
	proto.RegisterType((*CS_GetBroadCastSessions_Req)(nil), "MSG_CenterGate.CS_GetBroadCastSessions_Req")
	proto.RegisterType((*SC_GetBroadCastSessions_Rsp)(nil), "MSG_CenterGate.SC_GetBroadCastSessions_Rsp")
	proto.RegisterEnum("MSG_CenterGate.SUBMSG", SUBMSG_name, SUBMSG_value)
	proto.RegisterEnum("MSG_CenterGate.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("MSG_CenterGate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x4f, 0xc2, 0x30,
	0x18, 0xc6, 0xd9, 0x06, 0xe8, 0x5e, 0x0d, 0x34, 0x65, 0x09, 0x10, 0x2e, 0x84, 0x83, 0x21, 0x98,
	0x40, 0xa2, 0x67, 0x3d, 0xac, 0xea, 0xc2, 0x81, 0x48, 0xd6, 0x78, 0xd1, 0xc3, 0x52, 0x59, 0x21,
	0xd3, 0xd9, 0x61, 0x5b, 0x4d, 0xf8, 0x06, 0x7e, 0x0f, 0xbf, 0xa8, 0xd9, 0x8c, 0x12, 0x1a, 0x30,
	0xe1, 0xe0, 0x6d, 0x7b, 0xda, 0xa7, 0xef, 0xef, 0xfd, 0x07, 0xde, 0x84, 0x06, 0x11, 0xe1, 0x42,
	0x73, 0x19, 0x30, 0xcd, 0x87, 0x4b, 0x99, 0xe9, 0x0c, 0xd7, 0x36, 0xd5, 0xde, 0x05, 0x34, 0x08,
	0x8d, 0xa6, 0x29, 0x5b, 0x71, 0x79, 0x2b, 0xd2, 0x44, 0xf0, 0x28, 0xe4, 0xaf, 0xf8, 0x04, 0x6a,
	0xdf, 0xda, 0x38, 0xe6, 0x42, 0x27, 0xf3, 0x55, 0xcb, 0xea, 0x5a, 0x7d, 0x37, 0x34, 0xd4, 0xde,
	0x13, 0x34, 0x28, 0x31, 0xec, 0x6a, 0x89, 0x4f, 0xc1, 0x09, 0xb9, 0x2e, 0x3c, 0xb5, 0xb3, 0xf6,
	0xd0, 0x20, 0xb9, 0x96, 0x32, 0x93, 0x24, 0x8b, 0x79, 0x98, 0xdf, 0xda, 0x12, 0xcb, 0xde, 0x1a,
	0xeb, 0x12, 0xbc, 0x35, 0xea, 0x7c, 0xbe, 0x37, 0xeb, 0x33, 0x78, 0x6b, 0xd6, 0x1f, 0xff, 0x7f,
	0xc1, 0x3e, 0x40, 0x87, 0xd0, 0x28, 0xe0, 0xda, 0x97, 0x19, 0x8b, 0x09, 0x53, 0x9a, 0x72, 0xa5,
	0x92, 0x4c, 0xa8, 0x82, 0xb9, 0x0f, 0xf5, 0x4d, 0x83, 0x6a, 0x59, 0x5d, 0xa7, 0xef, 0x86, 0xa6,
	0x8c, 0x31, 0x94, 0xaf, 0x98, 0x66, 0x45, 0x98, 0xe3, 0xb0, 0xf8, 0xee, 0x7d, 0x58, 0xd0, 0xa1,
	0x64, 0xc7, 0xeb, 0xfb, 0x66, 0xb4, 0x05, 0xc5, 0xfe, 0x1b, 0xc5, 0x59, 0xa3, 0x0c, 0x3e, 0x2d,
	0xa8, 0xd2, 0x3b, 0x7f, 0x42, 0x03, 0xec, 0x42, 0xc5, 0xe7, 0x8b, 0x44, 0xa0, 0x12, 0x6e, 0x40,
	0xdd, 0x98, 0x2a, 0x64, 0xe5, 0xa2, 0x31, 0x2b, 0xc8, 0xc6, 0x1e, 0x20, 0xb3, 0xa9, 0xc8, 0xc9,
	0x55, 0xb3, 0x55, 0xa8, 0x8c, 0x3b, 0xd0, 0xdc, 0x51, 0x53, 0x54, 0xc9, 0x0f, 0x77, 0x94, 0x04,
	0x55, 0x07, 0x23, 0x70, 0x7f, 0xb3, 0xc6, 0x47, 0x70, 0x30, 0x16, 0xef, 0x2c, 0x4d, 0x62, 0x54,
	0xca, 0x7f, 0xe8, 0xdb, 0x6c, 0xc6, 0x95, 0x42, 0x16, 0x3e, 0x84, 0xf2, 0x0d, 0x4b, 0x52, 0x64,
	0xfb, 0xed, 0xfb, 0xe6, 0x8b, 0x5a, 0x4c, 0xf3, 0x95, 0x19, 0x6d, 0x96, 0xef, 0xb1, 0x5a, 0x2c,
	0xd2, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0xf4, 0x8d, 0x22, 0x60, 0x03, 0x00, 0x00,
}
