// Code generated by protoc-gen-go.
// source: MSG_CenterGate.proto
// DO NOT EDIT!

/*
Package MSG_CenterGate is a generated protocol buffer package.

It is generated from these files:
	MSG_CenterGate.proto

It has these top-level messages:
	CS_PlayerOnline_Req
	SC_PlayerOnline_Rsp
	CS_PlayerOffline_Req
	SC_PlayerOffline_Rsp
*/
package MSG_CenterGate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefan
// server
type SUBMSG int32

const (
	SUBMSG_Begin            SUBMSG = 0
	SUBMSG_CS_PlayerOnline  SUBMSG = 1
	SUBMSG_SC_PlayerOnline  SUBMSG = 2
	SUBMSG_CS_PlayerOffline SUBMSG = 3
	SUBMSG_SC_PlayerOffline SUBMSG = 4
)

var SUBMSG_name = map[int32]string{
	0: "Begin",
	1: "CS_PlayerOnline",
	2: "SC_PlayerOnline",
	3: "CS_PlayerOffline",
	4: "SC_PlayerOffline",
}
var SUBMSG_value = map[string]int32{
	"Begin":            0,
	"CS_PlayerOnline":  1,
	"SC_PlayerOnline":  2,
	"CS_PlayerOffline": 3,
	"SC_PlayerOffline": 4,
}

func (x SUBMSG) String() string {
	return proto.EnumName(SUBMSG_name, int32(x))
}
func (SUBMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorCode int32

const (
	ErrorCode_Invalid ErrorCode = 0
	ErrorCode_Success ErrorCode = 1
	ErrorCode_Fail    ErrorCode = 2
)

var ErrorCode_name = map[int32]string{
	0: "Invalid",
	1: "Success",
	2: "Fail",
}
var ErrorCode_value = map[string]int32{
	"Invalid": 0,
	"Success": 1,
	"Fail":    2,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// CS_PlayerOnline
type CS_PlayerOnline_Req struct {
	PlayerIdentify string `protobuf:"bytes,1,opt,name=PlayerIdentify" json:"PlayerIdentify,omitempty"`
}

func (m *CS_PlayerOnline_Req) Reset()                    { *m = CS_PlayerOnline_Req{} }
func (m *CS_PlayerOnline_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerOnline_Req) ProtoMessage()               {}
func (*CS_PlayerOnline_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// SC_PlayerOnline
type SC_PlayerOnline_Rsp struct {
	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,enum=MSG_CenterGate.ErrorCode" json:"Ret,omitempty"`
}

func (m *SC_PlayerOnline_Rsp) Reset()                    { *m = SC_PlayerOnline_Rsp{} }
func (m *SC_PlayerOnline_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerOnline_Rsp) ProtoMessage()               {}
func (*SC_PlayerOnline_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// CS_PlayerOffline
type CS_PlayerOffline_Req struct {
	PlayerIdentify string `protobuf:"bytes,1,opt,name=PlayerIdentify" json:"PlayerIdentify,omitempty"`
}

func (m *CS_PlayerOffline_Req) Reset()                    { *m = CS_PlayerOffline_Req{} }
func (m *CS_PlayerOffline_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerOffline_Req) ProtoMessage()               {}
func (*CS_PlayerOffline_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// SC_PlayerOffline
type SC_PlayerOffline_Rsp struct {
	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,enum=MSG_CenterGate.ErrorCode" json:"Ret,omitempty"`
}

func (m *SC_PlayerOffline_Rsp) Reset()                    { *m = SC_PlayerOffline_Rsp{} }
func (m *SC_PlayerOffline_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerOffline_Rsp) ProtoMessage()               {}
func (*SC_PlayerOffline_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CS_PlayerOnline_Req)(nil), "MSG_CenterGate.CS_PlayerOnline_Req")
	proto.RegisterType((*SC_PlayerOnline_Rsp)(nil), "MSG_CenterGate.SC_PlayerOnline_Rsp")
	proto.RegisterType((*CS_PlayerOffline_Req)(nil), "MSG_CenterGate.CS_PlayerOffline_Req")
	proto.RegisterType((*SC_PlayerOffline_Rsp)(nil), "MSG_CenterGate.SC_PlayerOffline_Rsp")
	proto.RegisterEnum("MSG_CenterGate.SUBMSG", SUBMSG_name, SUBMSG_value)
	proto.RegisterEnum("MSG_CenterGate.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("MSG_CenterGate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0xb6, 0x56, 0x33, 0x42, 0x1c, 0x26, 0x39, 0xe8, 0x4d, 0x72, 0x10, 0xa9, 0x50,
	0x41, 0xcf, 0x7a, 0xc8, 0xa2, 0xa1, 0x87, 0xa2, 0x64, 0xf1, 0x1c, 0x62, 0x33, 0x91, 0x85, 0xb0,
	0xa9, 0x9b, 0x55, 0xe8, 0xbf, 0x97, 0xad, 0x68, 0xe9, 0xde, 0x72, 0xdc, 0x8f, 0x7d, 0xcc, 0xf7,
	0x66, 0x20, 0x59, 0xc9, 0xbc, 0x14, 0xac, 0x2d, 0x9b, 0xbc, 0xb2, 0xbc, 0xd8, 0x98, 0xce, 0x76,
	0x14, 0x1d, 0xd2, 0xf4, 0x01, 0x62, 0x21, 0xcb, 0xd7, 0xb6, 0xda, 0xb2, 0x79, 0xd1, 0xad, 0xd2,
	0x5c, 0x16, 0xfc, 0x49, 0x57, 0x10, 0xfd, 0xb2, 0x65, 0xcd, 0xda, 0xaa, 0x66, 0x7b, 0x1e, 0x5c,
	0x06, 0xd7, 0x61, 0xe1, 0xd1, 0x34, 0x83, 0x58, 0x0a, 0x2f, 0xde, 0x6f, 0xe8, 0x06, 0x26, 0x05,
	0xdb, 0x5d, 0x26, 0xba, 0xbb, 0x58, 0x78, 0x26, 0x4f, 0xc6, 0x74, 0x46, 0x74, 0x35, 0x17, 0xee,
	0x57, 0xfa, 0x08, 0xc9, 0x5e, 0xa1, 0x69, 0x06, 0x3b, 0x08, 0x48, 0xf6, 0x0e, 0x7f, 0xf9, 0x81,
	0x12, 0x73, 0x05, 0x33, 0xf9, 0x96, 0xad, 0x64, 0x4e, 0x21, 0x1c, 0x65, 0xfc, 0xa1, 0x34, 0x8e,
	0x28, 0x86, 0x33, 0x6f, 0x39, 0x18, 0x38, 0xe8, 0x55, 0xc6, 0x31, 0x25, 0x80, 0x7e, 0x07, 0x9c,
	0x38, 0xea, 0x9b, 0xe1, 0x74, 0x7e, 0x0b, 0xe1, 0xff, 0x70, 0x3a, 0x85, 0xe3, 0xa5, 0xfe, 0xae,
	0x5a, 0x55, 0xe3, 0xc8, 0x3d, 0xe4, 0xd7, 0x7a, 0xcd, 0x7d, 0x8f, 0x01, 0x9d, 0xc0, 0xf4, 0xb9,
	0x52, 0x2d, 0x8e, 0xdf, 0x67, 0xbb, 0xd3, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x12, 0xff,
	0x9d, 0x7f, 0xd2, 0x01, 0x00, 0x00,
}
